name: Check for Successful Build
on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.target }} Compilation
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2022",
            # disabled pending fixes for `-Wchanges-meaning` errors
            # "ubuntu-latest",
            "macos-14"]
        target: ["editor", "template_debug", "template_release"]
        include:
          - os: "windows-2022"
            platform: windows
            additional-python-packages: pywin32
            shell: pwsh

          - os: "ubuntu-latest"
            platform: linux
            shell: bash
            
          - os: "macos-14"
            platform: macos
            shell: bash
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile native plugin
        uses: ./.github/actions/create-native-build
        with:
          platform: ${{ matrix.platform }}
          target: ${{ matrix.target }}
          shell: ${{ matrix.shell }}
          additional-python-packages: ${{ matrix.additional-python-packages }}

      - name: Run Tests
        if: matrix.platform == 'macos' && matrix.target == 'editor'
        run: |
          scons run_tests


  
