name: Check for Successful Build
on: [pull_request, workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.platform }} ${{ matrix.target }} Compilation
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2022",
            "ubuntu-24.04", # consider if best option (differs from FMOD's due to deprecation)
            "macos-14"] # consider if best option
        target: ["editor", "target_debug", "template_release"]
        include:
          - os: "windows-2022"
            platform: windows
            additional-python-packages: pywin32
            shell: pwsh

          - os: "ubuntu-24.04"
            platform: linux
            shell: bash
            
          - os: "macos-14"
            platform: macos
            shell: bash
      
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile native plugin
        uses: ./.github/actions/create-native-build
        with:
          platform: ${{ matrix.platform }}
          target: ${{ matrix.target }}
          shell: ${{ matrix.shell }}
          additional-python-packages: ${{ matrix.additional-python-packages }}


  