name: Check for Successful Build
on: [pull_request, workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows 10 Editor Compilation
            os: "windows-2022"
            platform: windows
            target: editor
            shell: pwsh
            additional-python-packages: pywin32
          
          - name: Ubuntu Editor Compliation 
            os: "ubuntu-24.04" # consider if best option (differs from FMOD's due to deprecation)
            platform: linux
            target: editor
            shell: bash

          - name: MacOS Editor Compilation
            os: "macos-14" # consider if best option
            platform: macos
            target: editor
            shell: bash
      
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          # ref: ${{ github.ref }}
          submodules: recursive

      - name: Compile native plugin
        uses: ./.github/actions/create-native-build
        with:
          platform: ${{ matrix.platform }}
          target: ${{ matrix.target }}
          shell: ${{ matrix.shell }}
          additional-python-packages: ${{ matrix.additional-python-packages }}


  